routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('home');
    
});
Route::get('/termsprivacy', function () {
    return view('termsprivacy');
    
});
Route::get('/signup', function () {
    return view('signup');
    
});
Route::get('/signin', function () {
    return view('login');
    
    
});



Route::resource('/forums','ForumController');
Route::get('/register_action','RegisterController@index');
Route::post('/register_action','RegisterController@store');

Route::get('/logout', function () {
    Auth::logout();
    return Redirect::to('');
})->middleware("auth");
Route::post('login_check','RegisterController@login');
Route::post('/forums/comments','CommentController@addComment');
    

app/forum.php
<?php

namespace App;

use App\Comment;
use Illuminate\Database\Eloquent\Model;
// use CyrildeWit\EloquentViewable\InteractsWithViews;
// use CyrildeWit\EloquentViewable\Contracts\Viewable;
class forum extends Model
{
    // use InteractsWithViews;

    protected $table='forums';
    public function comments(){
           return $this->morphMany('App\Comment','commentable');
    }
         
}

app/Http/Controllers/ForumController.php
<?php

namespace App\Http\Controllers;


use App\forum;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
class ForumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $forums = Forum::paginate(5); 
        return view("forum.index",compact('forums'));
    }

    
   
    public function create()
    {
      return view("forum.create"); 
    }
   


    public function store(Request $request)
    {
        
        $title=request('title');
        $description=request('description');
        $image=request('image');
        $str_slug=request('str_slug');
        $forums = new Forum;
        $forums->title=$title;
        $forums->str_slug= str_slug($title);
        $forums->description=$description;
        if($request->file('image')){
            $file = $request->file('image');
            $filename = time().'.'.$file->getClientOriginalExtension();
            $file->move('image',$filename);
            $forums->image=$filename;
        }
        $forums->save();
        
        return redirect('forums');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function show($str_slug)
    {
        $forums = Forum::where('id',$str_slug)->orWhere('str_slug',$str_slug)->first();
        return view('forum.show',compact('forums'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
     
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function destroy(forum $forum)
    {
        //
    }
}

resources/views/forum/create.blade.php
@extends('layout')
@section('forum')

<head>
    <script src="https://cdn.ckeditor.com/ckeditor5/19.0.0/classic/ckeditor.js"></script>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
       <div class="col-md-12">
            <div class="card">
                <div class="card-header">CREATE FORUM</div>
                <div class="card-body">
                    <form action="{{route('forums.store')}}" method="post" enctype="multipart/form-data" >
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <div class="form-group">
                        <input type="text" name="title" id="title" placeholder="Enter the Title" class="form-control">
                        </div>
                        <div class="form-group">
                        <label for="description">Description</label>
                        <textarea id="description" class ="form-controll"  name="description">
                        </textarea>
                        </div>
                        <script>
                            ClassicEditor
                                .create( document.querySelector( '#description' ) )
                                .catch( error => {
                                    console.error( error );
                                } );
                        </script>
                         <div class="form-group">   
                        <br/>
                         <input type="file" name="image" id="image" class="form-control">
                         
                            <br/>
                         <button type="submit" class="btn btn-success btn-block" >Create Forum</button>
                        </div>
                    </form>
                </div>
           
            </div>
        </div> 
    </div>
</div>
    </body>
    
<style>
    
    body{
                background-color: #023E7D;
            }
    .card {
        background: white;
        
        height: 300px;
        margin: 60px auto 81px auto;
        width:600px; 
    } 
    label[for=description]
    {
        margin-left: 50px;
    }
    input[type=text]
    {
        margin-top: 10px;
    }
    .card-header{
        background-color: #001233;
        height: 50px;
        width: auto;
        padding-top: 10px;
        font-size: 16px;
        font-family: verdana;
        padding-left: 25px;
        color: white;
        font-weight: bold;
        margin-top:100px;
    }
    .card-body{
        width: 100%;
        
        background-color: #f1f1f1;
    }

    #image{
        width: 500px;   
        margin-left: 50px;
    }
    #title{
        width: 500px;
        margin-left: 50px;
       
    }
    
    
</style>
@endsection

resources/views/forum/index.blade.php
@extends('layout')
@section('forum')
<div class="container">
<div class="containers">
  <div class="jumbotron">
    <h1>FORUM</h1>      
    <p>Berbagi dan Mencari Pengetahuan Seputar Gadget</p>
  </div>   
</div>

<style>
    .jumbotron{
        color:white;
        background: #004d99;
        text-align: center;
        margin-top: 70px;
        text-shadow: 2px 2px 4px black;
    }
    .jumbotron h1{
        font-family: sans-serif;
        
    }
    
</style>



<div class="box">
    <a href="{{route('forums.create')}}" class="create">Create Forum </a>
</div>
<style>
    
    .box .create{
        background-color: green;
        border-radius: 50px;
        border-style: solid;
        color: white;
        padding: 5px 5px 5px 5px;
        text-align: center;
        text-decoration:none;
        display: inline-block;
        font-size: 12px;
         margin-left: 1050px;
        cursor: pointer;
        font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }
 
</style>
</br>
<div class="warna">


    <div class="table responsive">
        <table class="table table-striped"  >
            <tr>
                <th>Thread </th>
                <th>Preview</th>
                <!-- <th>Views</th> -->
            </tr>
            @foreach ($forums as $row)                  
            <tr> 
                <td><h3><a href="{{route('forums.show', $row->str_slug)}}"><?php echo str_limit($row["title"],50); ?> </a></h3><?php echo str_limit($row["description"],200); ?></td>
                
                <td style="text-align: center;"><?php echo "<img src='image/".$row["image"]." ' width='200px; ' > ";    ?></td>
        
            </tr>


            @endforeach
        </table>
        <div class="rows">
            {!!$forums->links()!!}
        </div>
        <style>
            .rows{
                text-align: center;
            }

        </style>
    </div>
</div>
</div>
<style>
    .container{
    	background-color: #0466C8;
    }
    table {
        border-collapse: collapse;
        width: 100%;
    }
    th {
        text-align: center;
        padding: 8px;
        background-color:  #0040ff;
        color: white;
        width: 400px;
    }
    
    td{
        padding: 8px;
        text-align: left;
    }

    tr:nth-child(even){
        background-color: #f2f2f2;
    }

    .warna{
        
        background:  #e6ecff;
       
        background-size: cover
        
    }
</style>

@endsection

            

resources/views/forum/show.blade.php
@extends('layout')
@section('forum')
<body>
@if(session()->has('msg'))
<div class="alert alert-success ">
<a href="#" class="close" data-dismiss='alert' aria-label="close">x</a>
<h4 class="alert-heading">Well done!</h4>
  <p>Comment has been Add Successfully....</p>
  <hr>

</div>

<style>
    .alert{
        margin-top: 80px;
    }
</style>
@endif
<head>
    <script src="https://cdn.ckeditor.com/ckeditor5/19.0.0/classic/ckeditor.js"></script>
</head>
<div class="judul" >
    <h1>{{$forums['title']}}</h1> 
</div>
<div class="row justify-content-center">
    <div class="col-lg-6" style="color:white",border:>
        <?php echo $forums["description"]; ?>
</div>
    <div class="col-lg-2" >
        <?php echo "<img src='/image/".$forums["image"]."' width='250px;'> "; ?>
    </div>
   
</div>
<style>
    
    .judul{
        color: white;
        text-align: center;
        margin-bottom: 80px;
        margin-top: 80px;
        font-family:Verdana, Geneva;
    }
    .col-lg-2{
       justify-content: center;
       width: 300px;
       margin-left: 20px;;
    }
    .col-lg-6{
        text-align:left;

    }
    .row{
        margin-left: 300px;
    }
</style>
@foreach ($forums->comments() as $row)                  
        <h4><?php echo $row["content"]; ?></h4>

@endforeach
</body>       
</br>
</br>
    <div class="container">
        <div class="row justify-content-center">
           <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Add Comment</div>
                    <div class="card-body">
                        <form action="comments" method="post" >
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <div class="form-group">
                            <label for="content" style="color: white;">Your Comment</label>
                            <textarea id="content" class ="form-controll"  name="content">
                            </textarea>
                            </div>
                            <script>
                                ClassicEditor
                                    .create( document.querySelector( '#content' ) )
                                    .catch( error => {
                                        console.error( error );
                                    } );
                            </script>
                             <div class="form-group">   
                                <button type="submit" class="btn btn-success btn-block" >Ok</button>
                            </div>
                        </form>
                    </div>
               
                </div>
            </div> 
        </div>
    </div> 

        <style>
            body{
                background-color: #023E7D;
            }
            .card {
                background: inherit;
                height: 300px;
               
                width:500px; 
            } 
            label[for=description]
            {
                margin-left: 50px;
            }
            input[type=text]
            {
                margin-top: 10px;
            }
            .card-header{
                background-color: #001233;
                height: 50px;
                width: auto;
                padding-top: 10px;
                font-size: 16px;
                font-family: sans-serif;
                padding-left: 25px;
                color: white;
                font-weight: bold;
            }
            .card-body{
                width: 100%;
                
                background-color: inherit;
            }
        
            #image{
                width: 500px;   
                margin-left: 50px;
            }
            #title{
                width: 500px;
                margin-left: 50px;
               
            }
            
            
        </style>
@endsection